CREATE DATABASE HOMEWORK
USE HOMEWORK

CREATE TABLE EMPLOYEES
(
ID SMALLINT PRIMARY KEY IDENTITY,
NAME NVARCHAR(25)NOT NULL,
SURNAME NVARCHAR(30)NOT NULL,
SALARY SMALLINT CHECK(SALARY>=250),
EMAIL NVARCHAR(25) UNIQUE
)



INSERT INTO EMPLOYEES
VALUES
('xaliq','memmedov',280,'khalig@gmail.com'),
('ibrahim','qasimzade',250,'ibrahim@gmail.com'),
('rahid','kazimov',300,'rahid@gmail.com'),
('xeqani','memmedov',3000,'xeqani@gmail.com'),
('elsad','memmedov',500,'elsaf@gmail.com'),
('cefer','memmedov',2000,'cefer@gmail.com')

SELECT EMAIL FROM EMPLOYEES
WHERE SALARY BETWEEN 250 AND 500

SELECT * FROM EMPLOYEES
WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES)

SELECT COUNT(ID) AS COUNTEMPLOYEES FROM EMPLOYEES
WHERE SALARY<(SELECT AVG(SALARY) FROM EMPLOYEES)

SELECT ID, CONCAT(NAME,' ',SURNAME) AS FULLNAME,SALARY,EMAIL FROM EMPLOYEES
WHERE LEN(CONCAT(NAME,SURNAME))>15

SELECT * FROM EMPLOYEES
WHERE EMAIL LIKE '%gmail%' 

SELECT ((SELECT COUNT(SALARY) FROM EMPLOYEES WHERE SALARY>1000)*100/(SELECT COUNT(SALARY) FROM EMPLOYEES )) AS RESULT 

UPDATE EMPLOYEES
SET SALARY=250
WHERE SALARY=280

DELETE FROM EMPLOYEES
WHERE SALARY=280

SELECT * FROM EMPLOYEES

ALTER TABLE EMPLOYEES 
ADD CONSTRAINT TEST3 CHECK(SALARY<=19050)

ALTER TABLE EMPLOYEES
DROP CONSTRAINT TEST3


ALTER TABLE EMPLOYEES
ALTER COLUMN NAME NVARCHAR(30)

SELECT SUBSTRING(EMAIL,1,LEN(EMAIL)-10) AS EMAILRESULT FROM EMPLOYEES
WHERE EMAIL LIKE '%gmail.com'  

SELECT NAME,ASCII(NAME) AS ASCIIVALUE FROM EMPLOYEES --ASCII
WHERE SALARY>600


SELECT CONCAT(NAME,' ',SURNAME) AS FULLNAME FROM EMPLOYEES -- CONCAT

SELECT LEFT(NAME,3) AS LEFTNAME FROM EMPLOYEES --LEFT
WHERE SALARY>1000

SELECT REPLACE(NAME,'im','mi') FROM EMPLOYEES --REPLACE
WHERE NAME LIKE '%im'

SELECT REVERSE(NAME) FROM EMPLOYEES --REVERSE
WHERE ID>3










